accumulate_grad_batches: 1
amp: false
audio_num_mel_bins: 80
audio_sample_rate: 22050
base_config:
- ./base.yaml
binarization_args:
  reset_phone_dict: true
  reset_word_dict: true
  shuffle: false
  trim_eos_bos: false
  trim_sil: false
  with_align: true
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_spk_embed: false
  with_spk_id: true
  with_txt: true
  with_wav: false
  with_word: true
binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer
binary_data_dir: data/binary/LJSpeech
check_val_every_n_epoch: 10
clip_grad_norm: 1
clip_grad_value: 0
conv_use_pos: false
cwt_add_f0_loss: false
cwt_hidden_size: 128
cwt_layers: 2
cwt_loss: l1
cwt_std_scale: 0.8
debug: false
dec_dilations:
- 1
- 1
- 1
- 1
dec_ffn_kernel_size: 9
dec_inp_add_noise: false
dec_kernel_size: 5
dec_layers: 4
dec_num_heads: 2
decoder_rnn_dim: 0
decoder_type: fft
dict_dir: ''
diff_decoder_type: wavenet
diff_loss_type: l1
dilation_cycle_length: 1
dropout: 0.1
ds_workers: 2
dur_enc_hidden_stride_kernel:
- 0,2,3
- 0,2,3
- 0,1,3
dur_loss: mse
dur_predictor_kernel: 3
dur_predictor_layers: 2
enc_dec_norm: ln
enc_dilations:
- 1
- 1
- 1
- 1
enc_ffn_kernel_size: 9
enc_kernel_size: 5
enc_layers: 4
encoder_K: 8
encoder_type: fft
endless_ds: true
ffn_act: gelu
ffn_hidden_size: 1024
ffn_padding: SAME
fft_size: 1024
fmax: 7600
fmin: 80
frames_multiple: 1
gen_dir_name: ''
gen_tgt_spk_id: -1
griffin_lim_iters: 60
hidden_size: 256
hop_size: 256
infer: false
keep_bins: 80
lambda_commit: 0.25
lambda_energy: 0.1
lambda_f0: 1.0
lambda_ph_dur: 0.1
lambda_sent_dur: 1.0
lambda_uv: 1.0
lambda_word_dur: 1.0
layers_in_block: 2
load_ckpt: ''
loud_norm: false
lr: 1.0
max_beta: 0.06
max_epochs: 1000
max_frames: 1548
max_input_tokens: 1550
max_sentences: 48
max_tokens: 32000
max_updates: 200000
max_valid_sentences: 1
max_valid_tokens: 60000
mel_loss: ssim:0.5|l1:0.5
mel_vmax: 1.5
mel_vmin: -6
min_frames: 0
min_level_db: -100
num_ckpt_keep: 3
num_heads: 2
num_sanity_val_steps: -1
num_spk: 1
num_test_samples: 20
num_valid_plots: 10
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pitch_ar: false
pitch_embed_type: 0
pitch_enc_hidden_stride_kernel:
- 0,2,5
- 0,2,5
- 0,2,5
pitch_extractor: parselmouth
pitch_loss: l1
pitch_norm: standard
pitch_ssim_win: 11
pitch_type: frame
pre_align_args:
  allow_no_txt: false
  denoise: false
  sox_resample: false
  sox_to_wav: false
  trim_sil: false
  txt_processor: en
  use_tone: true
pre_align_cls: egs.datasets.audio.lj.pre_align.LJPreAlign
predictor_dropout: 0.5
predictor_grad: 0.1
predictor_hidden: -1
predictor_kernel: 5
predictor_layers: 2
pretrain_fs_ckpt: ''
print_nan_grads: false
processed_data_dir: data/processed/LJSpeech
profile_infer: false
raw_data_dir: data/raw/LJSpeech
ref_hidden_stride_kernel:
- 0,3,5
- 0,3,5
- 0,2,5
- 0,2,5
- 0,2,5
ref_level_db: 20
ref_norm_layer: bn
rename_tmux: true
residual_channels: 256
residual_layers: 20
resume_from_checkpoint: 0
save_best: true
save_codes: []
save_f0: false
save_gt: true
schedule_type: vpsde
scheduler: rsqrt
seed: 1234
sil_add_noise: false
sort_by_len: true
spec_max: []
spec_min: []
task_cls: modules.ProDiff.task.ProDiff_teacher_task.ProDiff_teacher_Task
tb_log_interval: 100
test_ids: []
test_input_dir: ''
test_num: 100
test_set_name: test
timescale: 1
timesteps: 4
train_set_name: train
train_sets: ''
use_cond_disc: true
use_energy_embed: true
use_gt_dur: true
use_gt_f0: true
use_pitch_embed: true
use_pos_embed: true
use_ref_enc: false
use_spk_embed: false
use_spk_id: false
use_split_spk_id: false
use_uv: true
use_var_enc: false
val_check_interval: 2000
valid_infer_interval: 10000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
var_enc_vq_codes: 64
vocoder_denoise_c: 0.0
warmup_updates: 2000
weight_decay: 0
win_size: 1024
word_size: 30000
work_dir: checkpoints/ProDiff_Teacher1
